grid-gap: 0
# <- property
#   ^ property
#      ^ property
#       ^ punctuation.delimiter
#         ^ number
grid-columns: 1
# <- property
#           ^ punctuation.delimiter
#             ^ number

header
# <- variable

body: "" {
  # <- constant
  # ^ punctuation.delimiter
  #   ^ string
  #      ^ punctuation.bracket
  grid-gap: 0
  # <- property
  #   ^ property
  #      ^ property
  #       ^ punctuation.delimiter
  #         ^ number
  grid-columns: 2
  # <- property
  #           ^ punctuation.delimiter
  #             ^ number

  content
  # <- variable
  sidebar
  # <- variable
}
# <- punctuation.bracket

footer
# <- variable
