shape: oval
label: ten
constraint: utehu
icon: huell
opacity: 1
fill: red
stroke: red
stroke-width: 5
stroke-dash: 4
border-radius: 1
font-color: red
shadow: true
multiple: true
animated: true
link: https://to
near: abc

hello

